### PR TITLE
Fortmatic is now non-custodial

### PR DESCRIPTION
**Pull request by rchen8**

### CODE REVIEW

**Comment by pcowgill** [comment]
@rchen8 Cool! What’s the best place to find more information about this change?

**Comment by rchen8** [comment]
https://medium.com/fortmatic/security-infrastructure-at-fortmatic-4a95c3688997

**Comment by shanefontaine** [comment]
Hey Richard. We discussed a bit and don't think they pass the "non-custodial"  check _in the context of this chart_. 

While Fortmatic themselves don't necessarily have control of the accounts, they have delegated control to AWS Cognito. The intended definition of non-custodial in this context was that there is _no_ reliance on 3rd parties at all.

Let me know if this makes sense and if you have any comments. If the above all sounds correct, I can go ahead and update the definition of non-custodial in the description section.

**Comment by rchen8** [comment]
Got it. So a sysadmin at AWS could theoretically steal all of Fortmatic users' coins?

Would be good to update the definition of non-custodial too.

**Comment by shanefontaine** [comment]
> So a sysadmin at AWS could theoretically steal all of Fortmatic users' coins?

Yes, technically.

I do not know how their system specifically works, but I would imagine that whomever has control of the AWS account that configured Cognito _may also_ be able to do the same. I do not know their system so this may or may not be true.

I'll update the definition now. :+1:

**Pull request closed without merging**
